name: Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - run: npm install yarn
      - run: yarn --cwd ragu-dom
        env:
          CI: true
      - run: yarn --cwd ragu-dom clean
        env:
          CI: true
      - run: yarn --cwd ragu-dom build
        env:
          CI: true
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: ragu-dom/dist
      - run: yarn --cwd ragu-server
        env:
          CI: true
      - run: yarn --cwd ragu-server clean
        env:
          CI: true
      - run: yarn --cwd ragu-server build
        env:
          CI: true
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: ragu-server/dist
      - run: yarn --cwd ragu-vue-server-adapter
        env:
          CI: true
      - run: yarn --cwd ragu-vue-server-adapter clean
        env:
          CI: true
      - run: yarn --cwd ragu-vue-server-adapter build
        env:
          CI: true
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: ragu-react-server-adapter/dist
